spring:
  application:
    name: task-management
  data:
    mongodb:
      uri: ${mongodb.uri}
      database: task-mgnt
  cloud:
    vault:
      enabled: true
      uri: http://localhost:8200
      token: MASTER-VAULT
      kv:
        backend: secret
        default-context: application
server:
  port: 8082

springdoc:
  api-docs:
    path: /openapi

logging:
  level:
    root: INFO
    cloudcode.gemini.services.task.management: INFO
  file:
    name: logs/api-audit.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: ${jwt-secret}
  expiration: 60000