application:
  api:
    path: /nimbus/api/v1.0

spring:
  application:
    name: task-management
  data:
    mongodb:
      #uri: ${mongodb.uri}
      uri: "mongodb://mazkte:t3st@localhost:27017/?authMechanism=SCRAM-SHA-256"
      database: task-mgnt
  cloud:
    vault:
      enabled: true
      uri: http://localhost:8200
      token: MASTER-VAULT
      kv:
        backend: secret
        default-context: application
server:
  port: 8082
  servlet:
    context-path: /nimbus

springdoc:
  api-docs:
    path: /openapi

logging:
  level:
    root: INFO
    cloudcode.gemini.services.task.management: INFO
  file:
    name: logs/api-audit.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  #secret: ${jwt-secret}
  secret: "CKqHITrMPzepvWmczHw+O4QpWgYKlX0b3hqrBxYWu2UWN9Xrr2zKq8ziOqMOfYiLSP5pJYR2FOoJpRGLUrGVeQ=="
  expiration: 60000